apiVersion: v1
kind: Service

metadata:
  name: notesappservice
  namespace: notesapp


spec:
  selector: 
    app: notesapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
  
