apiVersion: v1
kind: Service

metadata:
  name: customnginxservice
  namespace: customnginx

spec:
  selector: 
    app: customnginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

# customnginxservice.customnginx.svc.cluster.local
